<?php

include('../functions.php');

$codigo = $_POST['codigo'];
$preco = $_POST['preco'];
$nome = $_POST['nome'];
$descricao = $_POST['descricao'];
$especificacao = $_POST['especificacao'];
$aplicacao = $_POST['aplicacao'];
$marca = $_POST['marca'];
$codigo_produto = $_POST['codigo_produto'];
$ncm = $_POST['ncm'];
$garantia = $_POST['garantia'];
$lado = $_POST['lado'];
$posicao = $_POST['posicao'];
$codigo_barras = $_POST['codigo_barras'];
$peso_bruto = $_POST['peso_bruto'];
$codigo_montadora = $_POST['codigo_montadora'];
$consulte_manual = $_POST['consulte_manual'];
$direcao = $_POST['direcao'];
$assistencia_fabricante = $_POST['assistencia_fabricante'];
$tipo = $_POST['tipo'];
$caracteristicas = $_POST['caracteristicas'];
$composicao = $_POST['composicao'];
$rosca = $_POST['rosca'];
$medida = $_POST['medida'];
$diametro = $_POST['diametro'];
$diametro_rosca = $_POST['diametro_rosca'];
$sistema = $_POST['sistema'];
$quantidade_furos = $_POST['quantidade_furos'];
$diametro_furo_rolamento = $_POST['diametro_furo_rolamento'];
$comprimento = $_POST['comprimento'];
$relacao = $_POST['relacao'];
$quantidade_dentes = $_POST['quantidade_dentes'];
$material = $_POST['material'];
$modelo = $_POST['modelo'];
$fixacao = $_POST['fixacao'];
$dentes_internos = $_POST['dentes_internos'];
$combustivel = $_POST['combustivel'];
$ribs = $_POST['ribs'];
$numero_terminais = $_POST['numero_terminais'];
$torque_maximo_aperto_corque = $_POST['torque_maximo_aperto_corque'];
$localizacao = $_POST['localizacao'];
$pressao = $_POST['pressao'];
$geracao = $_POST['geracao'];
$motor = $_POST['motor'];
$cambio = $_POST['cambio'];
$tracao = $_POST['tracao'];
$codigo_peca_simplificado = $_POST['codigo_peca_simplificado'];
$rosca_lado_mecanico = $_POST['rosca_lado_mecanico'];
$rosca_lado_terminal = $_POST['rosca_lado_terminal'];
$rosca_lado_articulacao = $_POST['rosca_lado_articulacao'];
$diametro_interno = $_POST['diametro_interno'];
$grupo = $_POST['grupo'];
$largura = $_POST['largura'];
$diametro_externo = $_POST['diametro_externo'];
$subgrupo = $_POST['subgrupo'];
$id_categoria = $_POST['id_categoria'];
$classificacao = $_POST['classificacao'];
$status = $_POST['status'];
$multiplicador = $_POST['multiplicador'];

cadastrarProduto($conexao, $codigo, $nome, $preco, $descricao, $especificacao, $aplicacao, $marca, $codigo_produto, $ncm, $garantia, $lado, $posicao, $codigo_barras, $peso_bruto, $codigo_montadora, $consulte_manual, $direcao, $assistencia_fabricante, $tipo, $caracteristicas, $composicao, $rosca, $medida, $diametro, $diametro_rosca, $sistema, $quantidade_furos, $diametro_furo_rolamento, $comprimento, $relacao, $quantidade_dentes, $material, $modelo, $fixacao, $dentes_internos, $combustivel, $ribs, $numero_terminais, $torque_maximo_aperto_copo, $localizacao, $pressao, $geracao, $motor, $cambio, $tracao, $codigo_peca_simplificado, $rosca_lado_mecanismo, $rosca_lado_terminal, $rosca_lado_articulacao, $diametro_interno, $grupo, $largura, $diametro_externo, $subgrupo, $id_categoria, $classificacao, $status, $multiplicador);
